---
name: unix2dos
version: 0.01
author:
  - 'Michael Fuersich <michael.fuersich@arcor.de>'
abstract: implements unix2dos and dos2unix in pure perl
license: perl
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
provides:
  unix2dos:
    file: lib/unix2dos.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
